sudo: true

before_install:
  - tar -xzf /tmp/dynamodb_local_latest.tar.gz -C /tmp
  - java -Djava.library.path=/tmp/DynamoDBLocal_lib -jar /tmp/DynamoDBLocal.jar -inMemory &
  - sleep 2

services:
  - mongodb
  - couchdb
  - redis-server
  - elasticsearch

language: node_js
node_js:
  - "10"
  - "12"
  - "14"

branches:
  only:
    - master

notifications:
  email:
    - adriano@raiano.ch

env:
  global:
    - AWS_ACCESS_KEY_ID=AKID
    - AWS_SECRET_ACCESS_KEY=SECRET
    - AWS_REGION=us-east-1
    - AWS_DYNAMODB_ENDPOINT=http://localhost:8000
